# Generated by Django 4.2.16 on 2024-09-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_published_date_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Note',
        ),
    ]
